repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key

  - repo: https://github.com/crate-ci/typos
    rev: v1.23.6
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: rust-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        files: \.rs$
        pass_filenames: false

      - id: gleam-fmt
        name: gleam format
        entry: gleam format --check
        language: system
        files: \.gleam$
        pass_filenames: false
